<?php


function mymodule_theme($existing, $type, $theme, $path) {
    return [
        'node__person__full' => [
          'base hook' => 'node',
          'template'  => 'node--person--full',
        ],
       'node__view__persons' => [
            'template'  => 'node--view--persons',
          ]];

}
/**
 * Implements hook_preprocess_node().
 */
function mymodule_preprocess_node(&$variables) {

    $node = $variables['node'];
    if ($node->getType() == 'person') {
        $variables["name"]=$variables["content"]["field_name"][0]["#context"]["value"];
        $variables["body"]=$variables["content"]["body"][0]["#text"];
        $variables["mail"]=$variables["content"]["field_mail"][0]["#context"]["value"];
        $variables["image"]=$variables["content"]["field_image_person"][0]["#item"];
        $variables["adress"]=$variables["content"]["field_adress"][0]["#context"]["value"];

      }
 
  }



?>